#Preparing learning data
kappor_model <- read_excel("kapoor_model.xlsx")
mod_auto <- lm(auto~CNX,data=daily_return)
summary(mod_auto)
mod_bank <- lm(bank~CNX,data=daily_return)
summary(mod_bank)
mod_capgoods <- lm(capsgood~CNX,data=daily_return)
summary(mod_capgoods)
mod_consumer <- lm(consumer~CNX,data=daily_return)
summary(mod_consumer)
mod_fast <- lm(fast~CNX,data=daily_return)
summary(mod_fast)
mod_health <- lm(health~CNX, data=daily_return)
summary(mod_health)
mod_info <- lm(info~CNX, data=daily_return)
summary(mod_info)
mod_metals <- lm(metals~CNX, data=daily_return)
summary(mod_metals)
mod_oil <- lm(oil~CNX, data=daily_return)
summary(mod_oil)
mod_power <- lm(power~CNX, data=daily_return)
summary(mod_power)
mod_teleco <- lm(teleco~CNX, data=daily_return)
summary(mod_teleco)
daily_return$predict_teleco <- predict(mod_teleco,data=daily_return)
daily_return$error_predict_teleco <- (daily_return$teleco - daily_return$predict_teleco)
#1)Betas indicate how strong the correlation of the relation between 2 variables is
#2) The sectors with lowest BEtas are the least risky
#3) They will get similar results