library (readxl)
library (ggplot2)
library(GGally)
jaya <- read_excel("jayalaxmi.xlsx")
ggplot(data=jaya,aes(income_per_acre,loan_amount)) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(loan_repaid))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(loan_repaid))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(crop_insured))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(years_of_exp_in_sericulture))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(training_on_sericulture))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(krishi_pond))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(borewell_recharge))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(rain_harvesting))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(own_compost_manure))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(own_vermi_compost))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(trenching_mulching))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(bio_fertilizers))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(mechanization))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(mulberry_diseases))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(affected_by_pest))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(rearing_cost))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(instrument_mgmt_cost))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(temp_mgmt))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(humidity_mgmt))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(airvent_temp_mgmt))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(rotary_mounting))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(seri_total_subsidy))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,as.factor(chawki_bivol))) + geom_point()
ggplot(data=jaya,aes(income_per_acre,rearing_cost_missing)) + geom_point()
ggplot(jaya,aes(loan_amount,fill=as.factor(loan_repaid))) + geom_density(alpha=0.5)
ggplot(jaya,aes(income_per_acre,fill=as.factor(chawki_bivol))) + geom_density(alpha=0.5)
ggpairs(jaya)
