library(readxl)
library(tidyverse)
library(ggplot2)
library(ggbiplot)
grades <- read_excel("grades.xlsx",sheet="data")
grades$restaurant_type <- ifelse(grades$restaurant_type=="chain",0,1)
view(round(cor(grades),2))
#Density plots
ggplot(grades,aes(pageviews,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
#Split by treatment
grades_0 <- filter(grades,grades$treatment==0)
mean(grades_0$pageviews)
mean(grades_0$restaurant_type)
ggplot(grades_0,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
#split by restaurant or chain
grades_0_chain <- filter(grades_0,grades_0$restaurant_type==0)
grades_0_restaurant <- filter(grades_0,grades_0$restaurant_type==1)

mean(grades_0_chain$pageviews)
mean(grades_0_restaurant$pageviews)
mean(grades_0_chain$calls)
mean(grades_0_restaurant$calls)
mean(grades_0_chain$reservations)
mean(grades_0_restaurant$reservations)

ggplot(grades_0_chain,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_0_restaurant,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_0_chain,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_0_restaurant,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_0_chain,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_0_restaurant,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)

#grades_1
grades_1 <- filter(grades,grades$treatment==1)
mean(grades_1$pageviews)
mean(grades_1$restaurant_type)
ggplot(grades_1,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
grades_1_chain <- filter(grades_0,grades_0$restaurant_type==0)
grades_1_restaurant <- filter(grades_0,grades_0$restaurant_type==1)
mean(grades_1_chain$pageviews)
mean(grades_1_restaurant$pageviews)
mean(grades_1_chain$calls)
mean(grades_1_restaurant$calls)
mean(grades_1_chain$reservations)
mean(grades_1_restaurant$reservations)
ggplot(grades_1_chain,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_1_restaurant,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_1_chain,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_1_restaurant,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_1_chain,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_1_restaurant,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
#grades_2
grades_2 <- filter(grades,grades$treatment==2)
mean(grades_2$pageviews)
mean(grades_1$restaurant_type)
ggplot(grades_2,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
grades_2_chain <- filter(grades_0,grades_0$restaurant_type==0)
grades_2_restaurant <- filter(grades_0,grades_0$restaurant_type==1)
mean(grades_2_chain$pageviews)
mean(grades_2_restaurant$pageviews)
mean(grades_2_chain$calls)
mean(grades_2_restaurant$calls)
mean(grades_2_chain$reservations)
mean(grades_2_restaurant$reservations)
ggplot(grades_2_chain,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_2_restaurant,aes(pageviews,fill=as.factor(treatment))) + geom_density(alpha=0.5)
ggplot(grades_2_chain,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_2_restaurant,aes(calls,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_2_chain,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)
ggplot(grades_2_restaurant,aes(reservations,fill=as.factor(treatment),color=as.factor(treatment))) + geom_density(alpha=0.2)

grades %>% group_by(restaurant_type) %>% summarise(pagaviews=mean(pageviews),calls=mean(calls),
                                                   reservations=mean(reservations))
prcomp_grades <- prcomp(grades,center= TRUE,scale. = TRUE)
summary(prcomp_grades)
prcomp_grades$x
prcomp_grades$rotation
ggbiplot(prcomp_grades, varname.adjust = 3,varname.size = 2.5,alpha=0.1,size=0.4) +
  ylim(-2,2.5)+xlim(-3,2) + theme(axis.title = element_text(size=9))
mean(grades_0$pageviews)
#regression model
mod_calls <- lm(calls~as.factor(restaurant_type)+as.factor(treatment),grades)
summary(mod_calls)
mod_pageviews <- lm(pageviews~as.factor(restaurant_type)+as.factor(treatment)+as.factor(treatment):as.factor(restaurant_type),grades)
summary(mod_pageviews)
mod_pageviews_1 <- lm(pageviews~as.factor(restaurant_type)+as.factor(treatment),grades)
summary(mod_pageviews_1)
mod_pageviews_2 <- lm(pageviews~as.factor(restaurant_type):as.factor(treatment),grades)
summary(mod_pageviews_2)
mod_reservation_1 <- lm(reservations~as.factor(restaurant_type)+as.factor(treatment),grades)
summary(mod_reservation_1)
mod_reservation <- lm(reservations~as.factor(restaurant_type)+as.factor(treatment)+
                      as.factor(restaurant_type):as.factor(treatment),grades)
summary(mod_reservation)
treatment_1 <- filter(grades,grades$treatment<2)
mod_reservation_treatment_1 <- lm(reservations~as.factor(restaurant_type)+as.factor(treatment)+
                        as.factor(restaurant_type):as.factor(treatment),treatment_1)
summary(mod_reservation_treatment_1)
