library(tidyverse)
library(dplyr)
library(rpart)
library(rpart.plot)
library(caret)
library(randomForest)
smart <- read.csv("https://raw.githubusercontent.com/wdecisions/ba/master/smartphones.csv")
smart2 <- smart %>% filter(complete.cases(.))
d <- select(smart2,weight:release)
d$amoled <- factor(ifelse(smart2$display=="AMOLED","AMOLED","NO AMOLED"))
d$samsung <- factor(ifelse(smart2$brand=="Samsung",1,0))
d <- data.frame(d)
train_sample <- sample(1774,1395)
d_train <- d[train_sample,]
d_test <- d[-train_sample,]
set.seed(123)
rf <- randomForest(amoled ~., data=d_train,ntree=500,importance=T)
pred <- predict(rf,d_test)
confusionMatrix(pred,d_test$amoled,dnn=c("Predicted","Actual"))
varImpPlot(rf,type=1)
